# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(editable=True, verbose_name=b'Location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(editable=True, verbose_name=b'Product'))
            ],
        ),
        migrations.CreateModel(
            name='Instance', 
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ( 'product', models.ForeignKey('hkdb.product', on_delete=models.CASCADE) ),
                ( 'location', models.ForeignKey('hkdb.location', on_delete=models.CASCADE) ),
                ( 'lastModifyDate', models.DateTimeField(auto_now=True) ),
                ( 'lastModifyAuthor', models.TextField(editable=True, verbose_name=b'Editor') ),
            ]
        ),
    ]
