# Generated by Django 4.1.1 on 2022-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='ProductName'),
        ),
    ]
